### ISSUE TITLE
AttributeError: Method AffineNd is not a registered operator. Did you mean: []

### ISSUE THREAD

**Issue by yummy2108** [facebookresearch/video-long-term-feature-banks#38]
yumingjing@ubuntuh:~/video-long-term-feature-banks$ python2 tools/test_net.py --config_file configs/charades_r101_baseline.yaml 
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Found Detectron ops lib: /home/yumingjing/.local/lib/python2.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
/home/yumingjing/video-long-term-feature-banks/lib/core/config.py:427: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_config = AttrDict(yaml.load(fopen))
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[INFO: config.py:  369]: Config:
[INFO: config.py:  370]: {'AVA': {'ANNOTATION_DIR': 'data/ava/annotations',
         'DETECTION_SCORE_THRESH_EVAL': [0.85],
         'DETECTION_SCORE_THRESH_TRAIN': 0.9,
         'FORCE_TEST_FLIP': False,
         'FPS': 30,
         'FRAME_LIST_DIR': 'data/ava/frame_lists',
         'FULL_EVAL': True,
         'FULL_EVAL_DURING_TRAINING': False,
         'LFB_DETECTION_SCORE_THRESH': 0.9,
         'LFB_MAX_NUM_FEAT_PER_STEP': 5,
         'TEST_BOX_LISTS': ['ava_val_predicted_boxes.csv'],
         'TEST_LFB_BOX_LISTS': ['ava_val_predicted_boxes.csv'],
         'TEST_LISTS': ['val.csv'],
         'TEST_MULTI_CROP': False,
         'TEST_MULTI_CROP_SCALES': [224, 256, 320],
         'TEST_ON_TEST_SET': False,
         'TRAIN_BOX_LISTS': ['ava_train_v2.1.csv',
                             'ava_train_predicted_boxes.csv'],
         'TRAIN_LFB_BOX_LISTS': ['ava_train_predicted_boxes.csv'],
         'TRAIN_LISTS': ['train.csv'],
         'TRAIN_ON_TRAIN_VAL': False},
 'CHARADES': {'FPS': 24,
              'FRAME_LIST_DIR': 'data/charades/frame_lists',
              'LFB_CLIPS_PER_SECOND': 2,
              'NUM_TEST_CLIPS': 30,
              'NUM_TEST_CLIPS_DURING_TRAINING': 9,
              'NUM_TEST_CLIPS_FINAL_EVAL': 30,
              'TEST_LISTS': ['val.csv'],
              'TRAIN_LISTS': ['train.csv']},
 'CHECKPOINT': {'CHECKPOINT_MODEL': True,
                'CHECKPOINT_PERIOD': 4000,
                'CONVERT_MODEL': True,
                'DIR': '.',
                'RESUME': True},
 'CUDNN_WORKSPACE_LIMIT': 256,
 'DATADIR': 'data/charades/frames',
 'DATALOADER': {'MAX_BAD_IMAGES': 100},
 'DATASET': 'charades',
 'DATA_MEAN': [0.45, 0.45, 0.45],
 'DATA_STD': [0.225, 0.225, 0.225],
 'DEBUG': False,
 'EPIC': {'ANNOTATIONS': 'EPIC_train_action_labels.csv',
          'ANNOTATION_DIR': 'data/epic/annotations',
          'CLASS_TYPE': '',
          'FPS': 30,
          'FRAME_LIST_DIR': 'data/epic/frame_lists',
          'MAX_NUM_FEATS_PER_NOUN_LFB_FRAME': 10,
          'NOUN_LFB_FRAMES_PER_SECOND': 1,
          'TEST_LISTS': ['val.csv'],
          'TRAIN_LISTS': ['train.csv'],
          'VERB_LFB_CLIPS_PER_SECOND': 1},
 'FBO_NL': {'DROPOUT_RATE': 0.2,
            'INPUT_DROPOUT_ON': True,
            'INPUT_REDUCE_DIM': True,
            'LATENT_DIM': 512,
            'LFB_DROPOUT_ON': True,
            'NL_DROPOUT_ON': True,
            'NUM_LAYERS': 2,
            'PRE_ACT': True,
            'PRE_ACT_LN': True,
            'SCALE': True},
 'GET_TRAIN_LFB': False,
 'IMG_LOAD_RETRY': 10,
 'INTERPOLATION': 'INTER_LINEAR',
 'LFB': {'ENABLED': False,
         'FBO_TYPE': 'nl',
         'LFB_DIM': 2048,
         'LOAD_LFB': False,
         'LOAD_LFB_PATH': '',
         'MODEL_PARAMS_FILE': '',
         'NUM_LFB_FEAT': 500,
         'WINDOW_SIZE': 100,
         'WRITE_LFB': False},
 'LOG_PERIOD': 10,
 'MINIBATCH_QUEUE_SIZE': 64,
 'MODEL': {'ALLOW_INPLACE_RELU': True,
           'ALLOW_INPLACE_RESHAPE': True,
           'ALLOW_INPLACE_SUM': True,
           'BN_EPSILON': 1.0000001e-05,
           'BN_INIT_GAMMA': 0.0,
           'BN_MOMENTUM': 0.9,
           'DEPTH': 101,
           'DILATIONS_AFTER_CONV5': False,
           'FC_INIT_STD': 0.01,
           'FREEZE_BACKBONE': False,
           'MEAN': 114.75,
           'MEMONGER': True,
           'MODEL_NAME': 'resnet_video',
           'MULTI_LABEL': True,
           'NUM_CLASSES': 157,
           'SAMPLE_THREADS': 8,
           'STD': 57.375,
           'USE_AFFINE': True,
           'USE_BGR': False,
           'VIDEO_ARC_CHOICE': 4},
 'NONLOCAL': {'BN_EPSILON': 1.0000001e-05,
              'BN_INIT_GAMMA': 0.0,
              'BN_MOMENTUM': 0.9,
              'CONV3_NONLOCAL': True,
              'CONV4_NONLOCAL': True,
              'CONV_INIT_STD': 0.01,
              'LAYER_MOD': 2,
              'NO_BIAS': 0,
              'USE_AFFINE': True,
              'USE_BN': False,
              'USE_MAXPOOL': True,
              'USE_SCALE': True,
              'USE_SOFTMAX': True,
              'USE_ZERO_INIT_CONV': True},
 'NUM_GPUS': 8,
 'PROF_DAG': False,
 'RESNETS': {'NUM_GROUPS': 1,
             'STRIDE_1X1': False,
             'TRANS_FUNC': 'bottleneck_transformation_3d',
             'WIDTH_PER_GROUP': 64},
 'RNG_SEED': 2,
 'ROI': {'SCALE_FACTOR': 16, 'XFORM_RESOLUTION': 7},
 'ROOT_GPU_ID': 0,
 'SOLVER': {'BASE_LR': 0.02,
            'GAMMA': 0.1,
            'LRS': [1, 0.1],
            'LR_POLICY': 'steps_with_relative_lrs',
            'MAX_ITER': 24000,
            'MOMENTUM': 0.9,
            'NESTEROV': True,
            'SCALE_MOMENTUM': True,
            'SCALE_MOMENTUM_THRESHOLD': 1.1,
            'STEPS': [0, 20000, 24000],
            'STEP_SIZES': [20000, 4000],
            'WARMUP': {'WARMUP_END_ITER': 5000,
                       'WARMUP_ON': False,
                       'WARMUP_START_LR': 0.1},
            'WEIGHT_DECAY': 1.25e-05,
            'WEIGHT_DECAY_BN': 0.0},
 'TEST': {'BATCH_SIZE': 16,
          'CROP_SHIFT': 1,
          'CROP_SIZE': 256,
          'DATASET_SIZE': 1814,
          'DATA_TYPE': 'val',
          'PARAMS_FILE': '',
          'SAMPLE_RATE': 4,
          'SCALE': 256,
          'VIDEO_LENGTH': 32},
 'TRAIN': {'BATCH_SIZE': 16,
           'COMPUTE_PRECISE_BN': False,
           'CROP_SIZE': 224,
           'DATASET_SIZE': 7811,
           'DATA_TYPE': 'train',
           'DROPOUT_RATE': 0.3,
           'EVAL_PERIOD': 4000,
           'ITER_COMPUTE_PRECISE_BN': 200,
           'JITTER_SCALES': [256, 320],
           'PARAMS_FILE': 'pretrained_weights/r101_k400_pretrained.pkl',
           'PCA_EIGVAL': [0.225, 0.224, 0.229],
           'PCA_EIGVEC': [[-0.5675, 0.7192, 0.4009],
                          [-0.5808, -0.0045, -0.814],
                          [-0.5836, -0.6948, 0.4203]],
           'RESET_START_ITER': True,
           'RESUME_FROM_BATCH_SIZE': -1,
           'SAMPLE_RATE': 4,
           'TEST_AFTER_TRAIN': True,
           'USE_COLOR_AUGMENTATION': False,
           'VIDEO_LENGTH': 32},
 'USE_CYTHON': False}
[INFO: test_net.py:  110]: Done ResetWorkspace...
[WARNING: test_net.py:  114]: Testing started...
[WARNING: cnn.py:   25]: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
[INFO: charades.py:  195]: === Charades dataset summary ===
[INFO: charades.py:  196]: Split: val
[INFO: charades.py:  197]: Use LFB? False
[INFO: charades.py:  198]: Spatial shift position: 1
[INFO: charades.py:  199]: Number of videos: 1814
[INFO: charades.py:  202]: Number of frames: 1254921
[INFO: charades_data_input.py:   51]: Creating the execution context for worker_ids: [100, 101, 102, 103], batch size: 2
[INFO: data_input_helper.py:  157]: CREATING EXECUTION CONTEXT
[INFO: data_input_helper.py:  164]: POOLS: {}
[INFO: data_input_helper.py:  165]: SHARED DATA LISTS: 0
[INFO: data_input_helper.py:  177]: worker_id: 100 list: 1
[INFO: data_input_helper.py:  179]: worker_id: 100 list keys: [100]
[INFO: data_input_helper.py:  177]: worker_id: 101 list: 2
[INFO: data_input_helper.py:  179]: worker_id: 101 list keys: [100, 101]
[INFO: data_input_helper.py:  177]: worker_id: 102 list: 3
[INFO: data_input_helper.py:  179]: worker_id: 102 list keys: [100, 101, 102]
[INFO: data_input_helper.py:  177]: worker_id: 103 list: 4
[INFO: data_input_helper.py:  179]: worker_id: 103 list keys: [100, 101, 102, 103]
[INFO: data_input_helper.py:  224]: CREATED POOL: {100: <multiprocessing.pool.Pool object at 0x7f9858db3bd0>, 101: <multiprocessing.pool.Pool object at 0x7f985134bb90>, 102: <multiprocessing.pool.Pool object at 0x7f98525495d0>, 103: <multiprocessing.pool.Pool object at 0x7f984d41cf50>}
[INFO: data_input_helper.py:  225]: CREATED LISTS: 4
[INFO: data_input_helper.py:  226]: POOL keys: [100, 101, 102, 103]
[INFO: data_input_helper.py:  227]: LIST keys: [100, 101, 102, 103]
[WARNING: data_parallel_model.py:  157]: ** Only 4 GPUs available, GPUs [0, 1, 2, 3, 4, 5, 6, 7] requested
[INFO: data_parallel_model.py:  179]: Parallelizing model for devices: [0, 1, 2, 3, 4, 5, 6, 7]
[INFO: data_parallel_model.py:  202]: Create input and model training operators
[WARNING: data_parallel_model.py:  219]: 
[WARNING: data_parallel_model.py:  220]: ############# WARNING #############
[WARNING: data_parallel_model.py:  222]: Model CNN/<models.model_builder_video.ModelBuilder object at 0x7f992f3c0690> is used for testing/validation but
[WARNING: data_parallel_model.py:  223]: has init_params=True!
[WARNING: data_parallel_model.py:  224]: This can conflict with model training.
[WARNING: data_parallel_model.py:  225]: Please ensure model = ModelHelper(init_params=False)
[WARNING: data_parallel_model.py:  226]: ####################################
[WARNING: data_parallel_model.py:  227]: 
[INFO: data_parallel_model.py:  235]: Model for GPU : 0
[INFO: resnet_video.py:  150]: --------------- ResNet-101 1x64d-bottleneck_transformation_3d, charades, val, infer LFB? False, suffix: "_final_test" ---------------
[INFO: resnet_video.py:  166]: use_temp_convs_set: [[2], [1, 1, 1], [1, 0, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0]]
[INFO: resnet_video.py:  167]: temp_strides_set: [[1], [1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1]]
Traceback (most recent call last):
  File "tools/test_net.py", line 204, in <module>
    main()
  File "tools/test_net.py", line 200, in main
    test_net()
  File "tools/test_net.py", line 93, in test_net
    test_one_crop(lfb=lfb, suffix='_final_test')
  File "tools/test_net.py", line 125, in test_one_crop
    test_model.build_model(lfb=lfb, suffix=suffix, shift=shift)
  File "/home/yumingjing/video-long-term-feature-banks/lib/models/model_builder_video.py", line 123, in build_model
    lfb_infer_only=lfb_infer_only,
  File "/home/yumingjing/video-long-term-feature-banks/lib/models/model_builder_video.py", line 156, in create_data_parallel_model
    use_nccl=not cfg.DEBUG,
  File "/home/yumingjing/.local/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 39, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/yumingjing/.local/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 237, in Parallelize
    losses = forward_pass_builder_fun(model_helper_obj, loss_scale)
  File "/home/yumingjing/video-long-term-feature-banks/lib/models/model_builder_video.py", line 328, in model_creator
    suffix=suffix, lfb_infer_only=lfb_infer_only,
  File "/home/yumingjing/video-long-term-feature-banks/lib/models/resnet_video.py", line 183, in create_model
    bn_blob = model.AffineNd(conv_blob, 'res_conv1_bn', 64)
  File "/home/yumingjing/video-long-term-feature-banks/lib/models/model_builder_video.py", line 250, in AffineNd
    return self.net.AffineNd([blob_in, scale, bias], blob_out)
  File "/home/yumingjing/.local/lib/python2.7/site-packages/caffe2/python/core.py", line 2205, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method AffineNd is not a registered operator. Did you mean: []
[INFO: data_input_helper.py:  232]: Shutting down multiprocessing pools..
[INFO: data_input_helper.py:  234]: Shutting down pool 0
[INFO: data_input_helper.py:  234]: Shutting down pool 1
[INFO: data_input_helper.py:  234]: Shutting down pool 2
[INFO: data_input_helper.py:  234]: Shutting down pool 3
[INFO: data_input_helper.py:  241]: Pools closed
#-------------------------------------------------------------------------------------#
When I use tools/test_net.py on charades dataset. I wonder how to fix it! THX!

**Comment by chaoyuaw** [comment]
Hi @yummy2108 , Were you able to run the steps described in 
https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/INSTALL.md#caffe2
successfully? 

This repo uses an additional AffineNd operator, which is not in official caffe2. It seems that either the installation of our version of caffe2 wasn't successful, or the program is using an official caffe2 rather than ours.

**Comment by yummy2108** [comment]
Hi, thanks for your replying!
I have already successfully run the steps. And I even try to "make clean" and install again. But it didn't work.

**Comment by yummy2108** [comment]
Well ! I have solved the problem!
I pip uninstall the caffe and torch in my "/home/username/.local/lib/python2.7/site-packages/". And it run successfully ! And i get 40.4 mAP results on charades datasets! It's a great work! (*￣︶￣)

**Comment by yummy2108** [comment]
Hi ! I want to know is there any code or method for feature extraction ? THX

**Comment by chaoyuaw** [comment]
Hi @yummy2108 , Glad that you solved the issue! 

To construct LFB, what we do is essentially feature extraction. You could take a look at 
https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/tools/lfb_loader.py#L155
(, which is how we construct LFB) and modify it to meet your need.
